### ISSUE TITLE
Generating data form trained model

### ISSUE THREAD

**Issue by ajaigit** [GazzolaLab/Elastica-RL-control#3]
Hello PyElastica,

I wanted to know how can I generate time-series data from the RL model for different cases and write them to a text file. By data I mean the control input is given, the position of the tip of the robot, and time. I will be using this data to run a system identification algorithm which is part of my research. 
Any advice would be of great help.

Thank you.

**Comment by armantekinalp** [comment]
Hi @ajaigit,

In order to collect diagnostics of rods, you can use the [callback functionality](https://www.cosseratrods.org/software/pyelastica/) of PyElastica . Callback functions allows you to store the rod node positions, and time at every some step. You can also see an example callback function we use in RL model [here](https://github.com/GazzolaLab/Elastica-RL-control/blob/main/Case1/set_environment.py#L534). Note that callback will write the diagnostics inside a dictionary. After the simulation completed, you can access this dictionary and write the data into a text file. 

Storing the control input is similar to callback function but it is a little bit different. Control and actuations are applied as an external forcing on the rod using the [MuscleTorquesWithVaryingBetaSplines](https://github.com/GazzolaLab/Elastica-RL-control/blob/52e2f064ae59448bbb82735fa326a30b5405c667/Case1/MuscleTorquesWithBspline/BsplineMuscleTorques/muscle_torques_with_bspline_numba.py#L8) . You can pass a dictionary to this forcing class to record the applied actuation (muscle torques) and control (control points), i.e. `self.torque_profile_recorder` is a dictionary to record them. In order to see how we setup `MuscleTorquesWithVaryingBetaSplines` see [this](https://github.com/GazzolaLab/Elastica-RL-control/blob/main/Case1/set_environment.py#L521) .

**Comment by ajaigit** [comment]
Thank you so much for the detailed response. But for the line of code below I get an error: 
`from elastica.wrappers import (
        BaseSystemCollection,
        Connections,
        Constraints,
        Forcing,
        CallBacks)
from elastica.rod.cosserat_rod import CosseratRod
from elastica.boundary_conditions import OneEndFixedRod
from elastica.joint import FreeJoint, HingeJoint
from elastica.external_forces import GravityForces, UniformForces
from elastica.interaction import AnistropicFrictionalPlane`

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15784/3886989314.py in <module>
      3 from elastica.joint import FreeJoint, HingeJoint
      4 from elastica.external_forces import GravityForces, UniformForces
----> 5 from elastica.interaction import AnistropicFrictionalPlane

ImportError: cannot import name 'AnistropicFrictionalPlane' from 'elastica.interaction' (C:\Users\reach\anaconda3\envs\MyEnv\lib\site-packages\elastica\interaction.py)

**Comment by armantekinalp** [comment]
During the simulation using [callback function](https://www.cosseratrods.org/software/pyelastica/), we collect diagnostics of rod and write it into dictionary. After simulations are completed, we generally use scatter plot option of Matplotlib to generate videos. This is the fast option to see the motion of the rod.

For the publications, we use the [PovRay](https://www.povray.org) to render videos, it is open-source and gives good images. Please check our example scripts under [visualization](https://github.com/GazzolaLab/Elastica-RL-control/tree/main/visualization) folder.

**Comment by ajaigit** [comment]
@armantekinalp I did try running the example but I kept getting the following error:
`Traceback (most recent call last):
  File "generate_POVray_files.py", line 21, in <module>
    file1 = open("%s/moving_arm%02d.inc" % (dir_id, k),"w")
FileNotFoundError: [Errno 2] No such file or directory: './images/moving_arm00.inc'`
Although downloaded everything from the github page itself.

**Comment by armantekinalp** [comment]
@ajaigit I fixed the error, could you please try again. 

Error is because `./images/` directory was missing. Now when you run `generate_POVray_files.py`, if `./images/` is missing it will create and dump the `pov` and `inc` files there.

**Comment by ajaigit** [comment]
Thank you for fixing the error, I fixed it by creating the `image` directory in the specified path it was looking for.
