### ISSUE TITLE
How can we run the postprocessing scripts

### ISSUE THREAD

**Issue by sai-aneesh** [GazzolaLab/Elastica-RL-control#9]
Hi all,

I wanted to know how we can run the postprocessing scripts. Where do we get the 2 required positional arguments: 'rods_history' and 'sphere_history' from? (for case2)

**Comment by armantekinalp** [comment]
In order to use post processing scripts you have to collect the data. [Here](https://github.com/GazzolaLab/Elastica-RL-control/blob/main/Case2/set_environment.py#L633) in the script how we collect data from the simulation. To see how we call the post processing functions and which arguments we pass please check [this](https://github.com/GazzolaLab/Elastica-RL-control/blob/main/Case2/set_environment.py#L1015-L1033).

**Comment by sai-aneesh** [comment]
Okay I understood it now. First we train by running `logging_bio_args.py`
After training and getting the policy, we have to set `args.TRAIN = False` and run `logging_bio_args.py` again for getting post processing output. Is that right?

**Comment by armantekinalp** [comment]
Yes that is correct.
